import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import { QueryProvider } from "@/providers/query-provider";
import { ApolloWrapper } from "@/providers/apollo-provider";
import SheetProvider from "@/providers/sheet-provider";
import "./globals.css";

import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <head>
          <meta name="test" content="test" />
          <script src="https://cdn.shopify.com/shopifycloud/app-bridge.js" async />
        </head>
        <body className={inter.className}>
          <ApolloWrapper>
            <QueryProvider>
              <SheetProvider />
              {children}
            </QueryProvider>
          </ApolloWrapper>
          <Toaster />
          <Script
          src="https://cdn.shopify.com/shopifycloud/app-bridge.js"
          strategy="beforeInteractive"
        />
        </body>
      </html>
    </SessionProvider>
  );
}
